# Generated by Django 5.2.4 on 2025-08-06 08:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptomlog',
            name='date_logged',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
