# Generated by Django 5.2.4 on 2025-08-22 19:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appointmentbooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentbooking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointmentbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected'), ('Done', 'Done')], default='pending', max_length=10),
        ),
    ]
